### ISSUE TITLE
hdf5 format

### ISSUE THREAD

**Issue by wxz1996** [alex-sage/logo-gen#6]
Train myself data set. If I use hdf5 format, where should I change the code.

**Comment by alex-sage** [comment]
Hi, sorry for the very slow reply. I'm not quite sure if I understand your question though... The code supports datasets in hdf5 format, so you don't need to change the code. The loader assumes the data to be located in 'data' within the hdf5 file, if it is not you'll need to modify the path in `logo-gen/wgan/tflib/hdf5_images.py`.
